cc_command = [
    'RESET: 1',
    'SOFTWARE_REVISION: 4',

    'SELF_CHECK: 232',

    'LAST_CREDIT_OR_ERROR: 235',
    'EQUIPMENT_CATEGORY: 245',
    'MANUFACTURER_ID: 246',
    'PRODUCT_CODE: 244',
    'GET_SERIAL: 242',
    'SOFTWARE_COMMS_REVISION: 249',

    'REQUEST_COIN_ID: 184',
    'BUFFER_CREDIT: 159',
    'ACCEPT_COUNTER: 225',
    'GET_INSERT_COUNTER: 227',
    'GET_ACCEPT_COUNTER: 227',

    # MASTER INHIBIT STATUS
    'GET_MASTER_INHIBIT_STATUS: 227',
    'SET_MASTER_INHIBIT_STATUS: 228',

    # EVENT STREAM
    'READ_EVENT_BUFFER: 229',

    # INHIBIT
    'GET_INHIBIT_STATUS: 230',
    'SET_INHIBIT_STATUS: 231',

    'READ_INPUT_LINES: 227',

    'GET_STATUS: 248',
    'POLL: 254'
    ]

